services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=platform_user
      - POSTGRES_PASSWORD=platform_password
      - POSTGRES_DB=platform_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - platform-network

  api:
    build:
      context: .
      dockerfile: src/Platform.API/Dockerfile
    ports:
      - "5018:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=platform_db;Username=platform_user;Password=platform_password
    depends_on:
      - db
    networks:
      - platform-network

  studio:
    build:
      context: ./platform-studio
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - platform-network

volumes:
  postgres_data:


networks:
  platform-network:
    driver: bridge
